MODULE <test-module>
  FILE /tryInsideTry.kt
    CLASS CLASS MyException
      CONSTRUCTOR public constructor MyException(/*0*/ message: kotlin.String)
        BLOCK_BODY
          DELEGATING_CONSTRUCTOR_CALL Exception
            p0: GET_VAR message type=kotlin.String operator=null
          INSTANCE_INITIALIZER_CALL classDescriptor=MyException
    FUN public fun box(): kotlin.String
      BLOCK_BODY
        RETURN type=kotlin.Nothing from=box
          CALL .plus type=kotlin.String operator=PLUS
            $this: CONST String type=kotlin.String value='O'
            other: TRY_CATCH type=kotlin.String
              try: BLOCK type=kotlin.String operator=null
                TRY_CATCH type=kotlin.String
                  try: BLOCK type=kotlin.Nothing operator=null
                    THROW type=kotlin.Nothing
                      CALL .<init> type=java.lang.Exception operator=null
                        p0: CONST String type=kotlin.String value='oops!'
                  catch mye: BLOCK type=kotlin.String operator=null
                    CONST String type=kotlin.String value='1'
              catch e: BLOCK type=kotlin.String operator=null
                CONST String type=kotlin.String value='K'
